# Frontend Dockerfile
FROM node:20-alpine

WORKDIR /app

# Copier les fichiers package
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Exposer le port
EXPOSE 4200

# Commande de démarrage
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll"]
